CREATE TABLE `users` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `EMAIL_ADDRESS` varchar(256) NOT NULL,
  `PASSWORD` varchar(256) NOT NULL,
  `FIRST_NAME` varchar(256) NOT NULL,
  `LAST_NAME` varchar(256) NOT NULL,
  `AUTH_TOKEN` varchar(45) DEFAULT NULL,
  `TOKEN_CREATE_TIME` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL_ADDRESS_UNIQUE` (`EMAIL_ADDRESS`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
